# Generated by Django 2.1.3 on 2018-11-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organization_Name', models.CharField(help_text='Required. Maximum 200 Characters', max_length=200)),
                ('Contact_Person', models.CharField(help_text='Required. Maximum 50 Characters', max_length=50)),
                ('Email_id', models.CharField(help_text='Required. Maximum 50 Characters', max_length=50)),
                ('Mobile_no', models.CharField(help_text='Required. Maximum 10 Characters', max_length=10)),
                ('Address', models.CharField(help_text='Required. Door No and Street. Maximum 200 Characters', max_length=200)),
                ('Area', models.CharField(help_text='Required. Maximum 100 Characters', max_length=100)),
                ('City', models.CharField(help_text='Required. Maximum 50 Characters', max_length=50)),
                ('Pincode', models.CharField(help_text='Required. Maximum 6 Characters', max_length=6)),
                ('Website', models.CharField(help_text='Optional. Maximum 30 Characters', max_length=30)),
                ('Established_on', models.DateField(blank=True, help_text='Optional.', null=True)),
            ],
        ),
    ]
