# Generated by Django 2.1.3 on 2018-12-11 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import frugal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', frugal.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Credit_Point', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Product_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Requests')),
                ('Status', models.CharField(choices=[('P', 'Posted'), ('A', 'Accepted'), ('D', 'Declined')], default='P', max_length=1)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Donated_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Donations')),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Donor_Name', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('DOB', models.DateField(help_text='Required.')),
                ('Email_id', models.CharField(help_text='Maximum 50 Characters', max_length=50, primary_key=True, serialize=False)),
                ('Mobile_no', models.CharField(help_text='Should be 10 Characters', max_length=10)),
                ('Profile_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Profile_Photo')),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('Pincode', models.CharField(help_text='Should be 6 Characters', max_length=6, null=True)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest_Decline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(choices=[('N', 'Not Needed Now'), ('L', 'Donor Location is too Long'), ('D', 'Product Damaged'), ('O', 'Others')], default='N', max_length=1)),
                ('Comments', models.CharField(blank=True, max_length=200, null=True)),
                ('Donation_Interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donation_Interest')),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('Organization_Name', models.CharField(help_text='Maximum 200 Characters', max_length=200)),
                ('Contact_Person', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('Email_id', models.CharField(help_text='Maximum 50 Characters', max_length=50, primary_key=True, serialize=False)),
                ('Mobile_no', models.CharField(help_text='Should be 10 Characters', max_length=10)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('Pincode', models.CharField(help_text='Should be 6 Characters', max_length=6, null=True)),
                ('Website', models.CharField(blank=True, help_text='Maximum 30 Characters', max_length=30, null=True)),
                ('Established_on', models.DateField(help_text='Required.')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Detail', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='frugal/static/frugal/images/Activity')),
                ('Date', models.DateField()),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('C', 'Closed')], default='R', max_length=1)),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo_Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Detail', models.CharField(max_length=1000)),
                ('Sample_Photo', models.ImageField(upload_to='frugal/static/frugal/images/Need')),
                ('Need_Category', models.CharField(choices=[('O', 'One Time Need'), ('L', 'Life Time Need')], default='O', max_length=1)),
                ('Status', models.CharField(choices=[('O', 'Opened'), ('C', 'Closed')], default='O', max_length=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Category')),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overview', models.CharField(help_text='About your Organization', max_length=10000)),
                ('Cover_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Cover_photo')),
                ('Status', models.CharField(choices=[('R', 'Registered'), ('V', 'Verified'), ('A', 'Activated'), ('D', 'Deactivated')], default='R', max_length=1)),
                ('NGO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recognized_Body', models.CharField(max_length=100)),
                ('Registration_Number', models.CharField(max_length=100)),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Detail', models.CharField(max_length=1000)),
                ('Product_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Requests')),
                ('Status', models.CharField(choices=[('P', 'Posted'), ('C', 'Closed')], default='P', max_length=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('End_Date', models.DateField()),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Service_Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='post_donation',
            name='Product_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Product'),
        ),
        migrations.AddField(
            model_name='post_cause',
            name='Post_Donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Post_Donation'),
        ),
        migrations.AddField(
            model_name='post_cause',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Services'),
        ),
        migrations.AddField(
            model_name='ngo_need',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Product'),
        ),
        migrations.AddField(
            model_name='ngo_bid',
            name='Post_Donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Post_Donation'),
        ),
        migrations.AddField(
            model_name='donations',
            name='Donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donor'),
        ),
        migrations.AddField(
            model_name='donations',
            name='NGO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO'),
        ),
        migrations.AddField(
            model_name='donations',
            name='Product_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Product'),
        ),
        migrations.AddField(
            model_name='donation_interest',
            name='Donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donor'),
        ),
        migrations.AddField(
            model_name='donation_interest',
            name='Ngo_Need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Ngo_Need'),
        ),
    ]
