# Generated by Django 2.1.3 on 2018-12-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('Organization_Name', models.CharField(help_text='Maximum 200 Characters', max_length=200)),
                ('Contact_Person', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('Email_id', models.CharField(help_text='Maximum 50 Characters', max_length=50, primary_key=True, serialize=False)),
                ('Mobile_no', models.CharField(help_text='Should be 10 Characters', max_length=10)),
                ('Address', models.CharField(blank=True, help_text='Door No and Street. Maximum 200 Characters', max_length=200, null=True)),
                ('City', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('Pincode', models.CharField(help_text='Should be 6 Characters', max_length=6, null=True)),
                ('Website', models.CharField(blank=True, help_text='Maximum 30 Characters', max_length=30, null=True)),
                ('Established_on', models.DateField(help_text='Required.')),
            ],
        ),
        migrations.CreateModel(
            name='Ngo_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Detail', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='frugal/static/frugal/images/Activity')),
                ('Date', models.DateField()),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overview', models.CharField(help_text='About your Organization', max_length=10000)),
                ('Cover_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Cover_photo')),
                ('Status', models.CharField(choices=[('R', 'Registered'), ('V', 'Verified'), ('A', 'Activated'), ('D', 'Deactivated')], default='R', max_length=1)),
                ('NGO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recognized_Body', models.CharField(max_length=100)),
                ('Registration_Number', models.CharField(max_length=100)),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
    ]
