# Generated by Django 2.1.3 on 2018-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='Category_Name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
