# Generated by Django 2.1.3 on 2018-11-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='Area',
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Established_on',
            field=models.DateField(help_text='Required.'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Website',
            field=models.CharField(help_text='Optional. Maximum 30 Characters', max_length=30, null=True),
        ),
    ]
