# Generated by Django 2.1.3 on 2018-12-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0002_auto_20181206_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo_Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=30)),
                ('Count', models.IntegerField()),
                ('Detail', models.CharField(max_length=1000)),
                ('Photo', models.ImageField(upload_to='frugal/static/frugal/images/Need')),
                ('Need_Category', models.CharField(choices=[('O', 'One Time Need'), ('L', 'Life Time Need')], default='O', max_length=1)),
                ('Status', models.CharField(choices=[('O', 'Opened'), ('C', 'Closed')], default='O', max_length=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Category')),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
    ]
