# Generated by Django 2.1.3 on 2018-11-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0003_auto_20181119_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overview', models.CharField(help_text='About your Organization', max_length=10000)),
                ('Cover_Photo', models.ImageField(upload_to='pictures')),
                ('Status', models.CharField(choices=[('R', 'Registered'), ('V', 'Verified'), ('A', 'Activated'), ('D', 'Deactivated')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recognized_Body', models.CharField(help_text='Where you registered your Organization?', max_length=100)),
                ('Registration_Number', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='id',
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Email_id',
            field=models.CharField(help_text='Required. Maximum 50 Characters', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Mobile_no',
            field=models.CharField(help_text='Required. Should be 10 Characters', max_length=10),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Pincode',
            field=models.CharField(help_text='Required. Should be 6 Characters', max_length=6),
        ),
        migrations.AddField(
            model_name='ngo_registration',
            name='Email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO'),
        ),
        migrations.AddField(
            model_name='ngo_profile',
            name='Email_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO'),
        ),
    ]
