# Generated by Django 2.1.3 on 2018-11-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0004_auto_20181120_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_profile',
            old_name='Email_id',
            new_name='NGO',
        ),
        migrations.RenameField(
            model_name='ngo_registration',
            old_name='Email_id',
            new_name='NGO',
        ),
    ]
