# Generated by Django 2.1.3 on 2018-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0004_category_credit_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('Donor_Name', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('DOB', models.DateField(help_text='Required.')),
                ('Email_id', models.CharField(help_text='Maximum 50 Characters', max_length=50, primary_key=True, serialize=False)),
                ('Mobile_no', models.CharField(help_text='Should be 10 Characters', max_length=10)),
                ('Profile_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Profile_Photo')),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(help_text='Maximum 50 Characters', max_length=50)),
                ('Pincode', models.CharField(help_text='Should be 6 Characters', max_length=6, null=True)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
