# Generated by Django 2.1.3 on 2018-12-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0005_auto_20181207_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='ngo_need',
            name='Category',
        ),
        migrations.AlterField(
            model_name='ngo_need',
            name='Product_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Product'),
        ),
    ]
