# Generated by Django 2.1.3 on 2018-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0006_auto_20181126_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='Latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=13, null=True),
        ),
    ]
