# Generated by Django 2.1.3 on 2018-12-07 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0006_auto_20181207_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Product_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Requests')),
                ('Status', models.CharField(choices=[('P', 'Posted'), ('A', 'Accepted'), ('D', 'Declined')], default='P', max_length=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Donated_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Donations')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donor')),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Product')),
            ],
        ),
        migrations.RenameField(
            model_name='ngo_need',
            old_name='Photo',
            new_name='Sample_Photo',
        ),
        migrations.AddField(
            model_name='donation_interest',
            name='Ngo_Need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Ngo_Need'),
        ),
    ]
