# Generated by Django 2.1.3 on 2018-12-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0007_auto_20181207_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('Service_Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='ngo_need',
            old_name='Product_Name',
            new_name='Product',
        ),
        migrations.AddField(
            model_name='ngo_need',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frugal.Category'),
            preserve_default=False,
        ),
    ]
