# Generated by Django 2.1.3 on 2018-11-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0007_auto_20181126_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='Address',
            field=models.CharField(blank=True, help_text='Door No and Street. Maximum 200 Characters', max_length=200, null=True),
        ),
    ]
