# Generated by Django 2.1.3 on 2018-12-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0008_auto_20181208_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest_Decline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(choices=[('N', 'Not Needed Now'), ('L', 'Donor Location is too Long'), ('D', 'Product Damaged'), ('O', 'Others')], default='N', max_length=1)),
                ('Comments', models.CharField(blank=True, max_length=200, null=True)),
                ('Donation_Interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donation_Interest')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('R', 'Requested'), ('A', 'Accepted'), ('C', 'Closed')], default='R', max_length=1)),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count', models.IntegerField()),
                ('Detail', models.CharField(max_length=1000)),
                ('Product_Photo', models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Requests')),
                ('Status', models.CharField(choices=[('P', 'Posted'), ('C', 'Closed')], default='P', max_length=1)),
                ('Date', models.DateField(auto_now_add=True)),
                ('End_Date', models.DateField()),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Donor')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Product')),
            ],
        ),
        migrations.AddField(
            model_name='post_cause',
            name='Post_Donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Post_Donation'),
        ),
        migrations.AddField(
            model_name='post_cause',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Services'),
        ),
        migrations.AddField(
            model_name='ngo_bid',
            name='Post_Donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.Post_Donation'),
        ),
    ]
