# Generated by Django 2.1.3 on 2018-11-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0008_auto_20181127_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='Pincode',
            field=models.CharField(help_text='Should be 6 Characters', max_length=6, null=True),
        ),
    ]
