# Generated by Django 2.1.3 on 2018-12-05 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frugal', '0009_auto_20181129_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Detail', models.CharField(max_length=200)),
                ('Photo', models.ImageField(upload_to='frugal/static/frugal/images/Activity')),
                ('Date', models.DateField()),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frugal.NGO')),
            ],
        ),
        migrations.AlterField(
            model_name='ngo_profile',
            name='Cover_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='frugal/static/frugal/images/Cover_photo'),
        ),
    ]
